# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  libsodium_config = debug
  near_cli_cpp_config = debug

else ifeq ($(config),release)
  libsodium_config = release
  near_cli_cpp_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := libsodium near-cli-cpp

.PHONY: all clean help $(PROJECTS) Dependencies

all: $(PROJECTS)

Dependencies: libsodium

libsodium:
ifneq (,$(libsodium_config))
	@echo "==== Building libsodium ($(libsodium_config)) ===="
	@${MAKE} --no-print-directory -C near-cli-cpp/dependencies/libsodium -f Makefile config=$(libsodium_config)
endif

near-cli-cpp: libsodium
ifneq (,$(near_cli_cpp_config))
	@echo "==== Building near-cli-cpp ($(near_cli_cpp_config)) ===="
	@${MAKE} --no-print-directory -C near-cli-cpp -f Makefile config=$(near_cli_cpp_config)
endif

clean:
	@${MAKE} --no-print-directory -C near-cli-cpp/dependencies/libsodium -f Makefile clean
	@${MAKE} --no-print-directory -C near-cli-cpp -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   libsodium"
	@echo "   near-cli-cpp"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"